### ISSUE TITLE
'wifi_fpm_set_wakeup_cb' was not declared in this scope

### ISSUE THREAD

**Issue by H-LK** [ArduCAM/ArduCAM_ESP8266_UNO#8]
The function wifi_fpm_set_wakeup_cb isn't available in your ESP8266-Version. Works fine with ESP8266 2.3.0.
